import type { NextPage } from 'next';
import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head';
import HomePage from '../components/HomePage';

const Home: NextPage = () => {
  let { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t('common:title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="hreflang" />
      </Head>
      <HomePage />
    </div>
  );
};

export default Home;
